name: BuildImageWeb

on:
  push:
    tags:
      - "*"

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Check out current project
      uses: actions/checkout@v4
      with:
        path: ./Gnoss.Web.OpenCORE

    - name: check out commons
      uses: actions/checkout@v4
      with:
        repository: equipognoss/Gnoss.Commons.OpenCORE
        path: ./Gnoss.Commons
        ref: main

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get the tag name
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Gnoss.Web.OpenCORE/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

    - name: Build Nginx image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Gnoss.Web.OpenCORE/Dockerfile-nginx
        push: true
        tags: |
          ${{ secrets.DOCKER_IMAGE_NAME_NGINX }}:${{ steps.get_version.outputs.VERSION }}

    - name: Build Static image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Gnoss.Web.OpenCORE/Dockerfile-static
        push: true
        tags: |
          ${{ secrets.DOCKER_IMAGE_NAME_STATIC }}:${{ steps.get_version.outputs.VERSION }}